### ISSUE TITLE
nice: can't execute 'gnuplot': No such file or directory

### ISSUE THREAD

**Issue by spacejam** [PeterGrace/opentsdb-docker#11]
gnuplot does not seem to be accessible by opentsdb in this container

**Comment by spacejam** [comment]
this may correspond to the migration to alpine without also pulling in gnuplot to compensate for the dep loss

**Comment by pomarc** [comment]
I confirm this issue. Just deployed the image on cloud.docker.com, opentsdb starts nicely, accepts input but when plotting, "nice: can't execute 'gnuplot': No such file or directory"

**Comment by PeterGrace** [comment]
Hi spacejam,

As @CheRuisiBesares linked to this issue, can you retest and see if the problem is resolved?  Docker Hub sometimes takes a bit of time to regenerate the image after a commit, so you might want to wait till tomorrow to have a check.

Thanks!

Pete

**Comment by spacejam** [comment]
Hey! #14 seems like it likely addresses this! I'm a bit overloaded currently, as I've recently moved to a new country and have been a bit underwater with logistics as well as catching up for work. No guarantees about my ability to test this soon, but I am hopeful based on the diff!

The specific way I'd test this would be to just pump a metric into opentsdb and then try to hit the built-in web UI to plot that metric. If an actual graph pops up, it works.  If it says `can't execute 'gnuplot': No such file or directory` then there may be a small path issue that needs to be resolved.

**Comment by spacejam** [comment]
Just tested, works well!  Thanks!
