### ISSUE TITLE
Gnuplot stderr:  nice: can't execute 'gnuplot': Permission denied

### ISSUE THREAD

**Issue by pomarc** [PeterGrace/opentsdb-docker#12]
executing the image on docker cloud, opentsdb and hbase start fine, data can be sent to the opentsdb daemon and it's received fine. 
But I have the following error when trying to get a plot:    

 Request failed: Bad Request
     <pre>Gnuplot stderr:

```
     nice: can't execute 'gnuplot': Permission denied
 </pre>
```

**Comment by PeterGrace** [comment]
Hi pomarc!

Can you please retest and see if the issue is resolved for you?  @CheRuisiBesares just submitted a PR  that should resolve the issue.

Thanks!
Pete
