### ISSUE TITLE
Old version of go-dnsmasq? Still seeing 'You need to specify some search domains'

### ISSUE THREAD

**Issue by pashap** [PeterGrace/opentsdb-docker#15]
Hi, regarding #14 and https://github.com/janeczku/docker-alpine-kubernetes/issues/9:

I believe the `janeczku/alpine-kubernetes:3.2` image was built one day after(8 days ago) the latest `petergrace/opentsdb-docker`(9 days ago), which causes the 'You need to specify some search domains' error. 

Here are their builds:
https://hub.docker.com/r/janeczku/alpine-kubernetes/builds/

## My local images:
```
janeczku/alpine-kubernetes   3.2                 4df7a36a6843        8 days ago          10.98 MB
petergrace/opentsdb-docker   latest              7dbffc0e8648        9 days ago          731.5 MB
```

## The output from opentsdb container:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
Sleeping for 30 seconds to give HBase time to warm up
starting hbase
time="2016-06-15T16:39:29Z" level=fatal msg="You need to specify some search domains"
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[services.d] done.
[s6-finish] sending all processes the TERM signal.
stopping hbase
[s6-finish] sending all processes the KILL signal and exiting.
```

## And this is where we can see mismatched versions of `go-dnsmasq`
```
$ docker run --entrypoint /bin/bash -ti -p 4242:4242 petergrace/opentsdb-docker
bash-4.3# go-dnsmasq --version
go-dnsmasq-minimal version 1.0.5
```

```
docker run --entrypoint /bin/sh -ti janeczku/alpine-kubernetes:3.2
/ # go-dnsmasq --version
go-dnsmasq version 1.0.6
```

Is it just a matter of a new docker build/push to docker hub? 

Thanks!

cc @CheRuisiBesares

**Comment by CheRuisiBesares** [comment]
@pashap seems like you are right. We will need to rebuild the container one more time to get all the deps in order I believe.

**Comment by pashap** [comment]
@PeterGrace any updates on this?

**Comment by PeterGrace** [comment]
Sorry that I've missed this.  I just triggered a fresh image build, let me know if this resolves the issue for you.

**Comment by pashap** [comment]
Awesome, much appreciated. Just pulled latest and go-dnsmasq looks up to date:
```
bash-4.3# go-dnsmasq --version
go-dnsmasq version 1.0.6
bash-4.3#
```
