### ISSUE TITLE
Connecting client to OpenTSDB

### ISSUE THREAD

**Issue by lemquan** [PeterGrace/opentsdb-docker#17]
Silly question, I can not seem to connect to OpenTSDB. I am able to run the docker image, and reach the web interface at port 4242. I am using the Python client from postdb. Most connections require the host name and port. I was under the impression the host name is "0.0.0.0" and the port is 4242. I want to start this connection to insert and query data. 

Has anyone connected to this instance using a client?

**Comment by soeren-lubitz** [comment]
the host is for a local setup localhost:4242 but depending on your ipv6 config this could not work because it resolves to ::1. so using 127.0.0.1 worked like a charm for my setup

**Comment by PeterGrace** [comment]
Hi @lemquan and sorry for the delay.  I can indeed send data to this container via scollector (which is how I test it normally) -- if this problem still persists for you I'd suggest trying the latest image that I'll be uploading today and then reopen this issue if the problem still occurs.
