### ISSUE TITLE
update opentsdb.conf

### ISSUE THREAD

**Issue by NitinRanjan** [PeterGrace/opentsdb-docker#23]
how can I update opentsdb.conf 
tsd.core.meta.enable_realtime_uid 
tsd.core.meta.enable_tsuid_tracking 
tsd.core.meta.enable_tsuid_incrementing 
tsd.core.meta.enable_realtime_ts 
tsd.http.query.allow_delete

I need to make these value true.

I am using PeterGrace/opentsdb-docker

**Comment by rDr4g0n** [comment]
I needed an `opentsdb.conf` as well. It's easy to add, but you will need to rebuild the image. Here is my patch:

https://github.com/rDr4g0n/opentsdb-docker/commit/f10020b09273e34e10335c0d6fe0c6f72b778d81

**Comment by raphaelquati** [comment]
You can create a localfile, and map the directory (volume) to "/etc/opentsdb"

**Comment by PeterGrace** [comment]
The new dockerfile I'll be pushing today will make it easier to import your own opentsdb.conf file when running the image.  Thanks for the suggestion!
