### ISSUE TITLE
Push 2.3 version on Docker hub

### ISSUE THREAD

**Issue by sanel** [PeterGrace/opentsdb-docker#25]
Hi,

Seems like https://hub.docker.com/r/petergrace/opentsdb-docker is still pulling the old, 2.2 OpenTSDB version, but github repo is using 2.3.

Any chance Docker hub can be updated?

Thanks!

**Comment by larssb** [comment]
Please do yes!

**Comment by PeterGrace** [comment]
I'll be pushing an updated Dockerfile in a few minutes!

**Comment by PeterGrace** [comment]
Latest image has 2.3.1!

**Comment by sanel** [comment]
Thanks!
