### ISSUE TITLE
Chunked content

### ISSUE THREAD

**Issue by asrenzo** [PeterGrace/opentsdb-docker#32]
Hi,

Even if your Dockerfile provides : 

- tsd.http.request.enable_chunked = true
- tsd.http.request.max_chunk = 1000000

I'm only able to load a very small number of point at a time (less than 50). If I try to increase this number, I always receive this error : Chunked request not supported

Any idea ?

Regards,

Laurent

**Comment by PeterGrace** [comment]
Hi @asrenzo, I maintain the docker container, but questions like this might be better fielded with the opentsdb crew over at https://github.com/OpenTSDB/opentsdb.
