### ISSUE TITLE
Error message when building the Dockerimage 

### ISSUE THREAD

**Issue by LeducH** [PeterGrace/opentsdb-docker#37]
I want to build the docker image by using 

    docker build -t my-opentsb . 

unfortunately  I get the error message 

```
The command '/bin/sh -c apk add --virtual builddeps     ${BUILD_PACKAGES}   && : Install OpenTSDB and scripts   && wget --no-check-certificate     -O v${TSDB_VERSION}.zip     https://github.com/OpenTSDB/opentsdb/archive/v${TSDB_VERSION}.zip   && unzip v${TSDB_VERSION}.zip   && rm v${TSDB_VERSION}.zip   && cd /opt/opentsdb/opentsdb-${TSDB_VERSION}   && echo "tsd.http.request.enable_chunked = true" >> src/opentsdb.conf   && echo "tsd.http.request.max_chunk = 1000000" >> src/opentsdb.conf   && ./build.sh   && cp build-aux/install-sh build/build-aux   && cd build   && make install   && cd /   && rm -rf /opt/opentsdb/opentsdb-${TSDB_VERSION}' returned a non-zero code: 2
```

Moreover here is the complete console output [ix.io](http://ix.io/27D4)

Most likely the maven address is updated since opening the  [maven address](http://central.maven.org/maven2/commons-logging/commons-logging/1.1.1)

```
501 HTTPS Required. 
Use https://repo1.maven.org/maven2/
More information at https://links.sonatype.com/central/501-https-required 
```

Where can this be adjusted

**Comment by mcauto** [comment]
@LeducH 

https://github.com/OpenTSDB/opentsdb/issues/1899

check v2.5.0 milestone

**Comment by PeterGrace** [comment]
Thanks so much for reporting this issue.  I am archiving this repo as it seems no longer relevant in today's environment.
