### ISSUE TITLE
4242 port connection refused after docker stop container

### ISSUE THREAD

**Issue by sqbing** [PeterGrace/opentsdb-docker#6]
Docker version: 1.3.2
OS version: CentOS release 6.5
CMD: docker run -tdi -p 4242:4242 petergrace/opentsdb-docker:latest
Newly created container's 4242 port can be visited after running container about 1 minute, but restarted container can no longer be visited.

**Comment by sqbing** [comment]
After manually running /opt/sei-bin/create_tsdb_tables.sh, opentsdb starts up.
According to logs in /var/log/supervisor, seems opentsdb can't find table 'tsdb' in hbase.

**Comment by PeterGrace** [comment]
I'm closing this issue since it is quite old and I've made updates to the image.  If you're still having an issue after using a more recent pull of the image, please feel free to reopen this issue.
