### ISSUE TITLE
Please add a license to your project

### ISSUE THREAD

**Issue by lukaspustina** [PeterGrace/opentsdb-docker#8]
Hi Peter,

thanks for preparing this Dockerfile. I'd like to reuse it, but unfortunately, your repository lacks a license permitting reuse. Would you mind adding a license?

Thanks,
Lukas

**Comment by PeterGrace** [comment]
Hello Lukas,

I've uploaded the MIT license in commit #c7ab57b4d037bf0d67ff2d1c6b4ad86b587755d8

Thanks for pointing this out!

**Comment by lukaspustina** [comment]
Thanks!
